### ISSUE TITLE
Select 3 interesting stories of mathematicians

### ISSUE THREAD

**Issue by ahammadshawki8** [ahammadshawki8/Math-and-Programming#20]
For the Programmers story, I will write
- Ada Lovelace
- Alan Turing
- Guido van Russom
- Steve Jobs
- Finally mine xD

You have to write 3 stories of mathematicians
Choose some interesting but uncommon stories.

**Comment by Arko07-quanta** [comment]
Here are some propsals:
1. Ramanujan
2. Gauss
3. Euler
4. Évariste Galois
5. George Cantor

**Comment by ahammadshawki8** [comment]
Choose the most interesting 3 which are uncommon I think Eular's one is common, I will search for interesting parts in Guido's life, if I can't find much, then will go for Elon Musk, it will be hit 😎

**Comment by ahammadshawki8** [comment]
Choose the most interesting 3 which are uncommon I think Eular's one is common, I will search for interesting parts in Guido's life, if I can't find much, then will go for Elon Musk, it will be hit 😎

**Comment by Arko07-quanta** [comment]
Elon Musk???Seriously??

**Comment by Arko07-quanta** [comment]
BTW, I will have to find a suitable platform to write. Since I don't have microsoft office rn. Google docs should work fine

**Comment by Arko07-quanta** [comment]
Select any 3 from above

**Comment by ahammadshawki8** [comment]
I think Eular, Gauss, Galois stories are common. You can write Ramanujan
and Cantor stories, also can you write the story of Newton/Einstein?

**Comment by Arko07-quanta** [comment]
Einstein's personal life is very interesting
